/* Autogenerated by MaKL - Wed Dec 14 14:34:49 CET 2011 */
/* Configure arguments: --libs=/Users/tho/work/IOTCPE/kink/stage --prefix=/Users/tho/work/IOTCPE/kink/stage --enable_debug --enable_warns */

#ifndef _EVCOAP_CONF_H_
#define _EVCOAP_CONF_H_

#undef EVCOAP_VERSION
#define EVCOAP_VERSION "0.0.0beta"

#undef EVCOAP_VERSION_MAJOR
#define EVCOAP_VERSION_MAJOR 0

#undef EVCOAP_VERSION_MINOR
#define EVCOAP_VERSION_MINOR 0

#undef EVCOAP_VERSION_TEENY
#define EVCOAP_VERSION_TEENY 0

#undef OS_DARWIN
#define OS_DARWIN 1

#undef PRE_LDADD
#define PRE_LDADD -ldl

#undef EVCOAP_DEBUG
#define EVCOAP_DEBUG 1

#undef HAVE_LIBEVENT
#define HAVE_LIBEVENT 1

#undef HAVE_LIBU
#define HAVE_LIBU 1

#undef DESTDIR
#define DESTDIR "/Users/tho/work/IOTCPE/kink/stage"

#undef BINDIR
#define BINDIR "/Users/tho/work/IOTCPE/kink/stage/bin"

#undef SBINDIR
#define SBINDIR "/Users/tho/work/IOTCPE/kink/stage/sbin"

#undef CONFDIR
#define CONFDIR "/Users/tho/work/IOTCPE/kink/stage/etc"

#undef INCDIR
#define INCDIR "/Users/tho/work/IOTCPE/kink/stage/include"

#undef LIBDIR
#define LIBDIR "/Users/tho/work/IOTCPE/kink/stage/lib"

#undef SHLIBDIR
#define SHLIBDIR "/Users/tho/work/IOTCPE/kink/stage/lib"

#undef LIBEXDIR
#define LIBEXDIR "/Users/tho/work/IOTCPE/kink/stage/libexec"

#undef VARDIR
#define VARDIR "/Users/tho/work/IOTCPE/kink/stage/var"

#undef SHAREDIR
#define SHAREDIR "/Users/tho/work/IOTCPE/kink/stage/share"

#undef MANDIR
#define MANDIR "/Users/tho/work/IOTCPE/kink/stage/share/man"

#undef DOCDIR
#define DOCDIR "/Users/tho/work/IOTCPE/kink/stage/share/doc"

#endif /* !_EVCOAP_CONF_H_ */
