/* Autogenerated by MaKL - Wed Dec 14 12:16:58 CET 2011 */
/* Configure arguments: --libs=/Users/tho/work/IOTCPE/kink/stage */

#ifndef _EVCOAP_CONF_H_
#define _EVCOAP_CONF_H_

#undef EVCOAP_VERSION
#define EVCOAP_VERSION "0.0.0beta"

#undef EVCOAP_VERSION_MAJOR
#define EVCOAP_VERSION_MAJOR 0

#undef EVCOAP_VERSION_MINOR
#define EVCOAP_VERSION_MINOR 0

#undef EVCOAP_VERSION_TEENY
#define EVCOAP_VERSION_TEENY 0

#undef OS_DARWIN
#define OS_DARWIN 1

#undef PRE_LDADD
#define PRE_LDADD -ldl

#undef HAVE_LIBEVENT
#define HAVE_LIBEVENT 1

#undef HAVE_LIBU
#define HAVE_LIBU 1

#undef DESTDIR
#define DESTDIR "/usr/local"

#undef BINDIR
#define BINDIR "/usr/local/bin"

#undef SBINDIR
#define SBINDIR "/usr/local/sbin"

#undef CONFDIR
#define CONFDIR "/usr/local/etc"

#undef INCDIR
#define INCDIR "/usr/local/include"

#undef LIBDIR
#define LIBDIR "/usr/local/lib"

#undef SHLIBDIR
#define SHLIBDIR "/usr/local/lib"

#undef LIBEXDIR
#define LIBEXDIR "/usr/local/libexec"

#undef VARDIR
#define VARDIR "/usr/local/var"

#undef SHAREDIR
#define SHAREDIR "/usr/local/share"

#undef MANDIR
#define MANDIR "/usr/local/share/man"

#undef DOCDIR
#define DOCDIR "/usr/local/share/doc"

#endif /* !_EVCOAP_CONF_H_ */
