include common.mk
include ../Makefile.conf

INCS = kink_conf.h

INCS += evcoap.h
INCS += evcoap_base.h
INCS += evcoap_cli.h
INCS += evcoap_enums.h
INCS += evcoap_flow.h
INCS += evcoap_net.h
INCS += evcoap_opt.h
INCS += evcoap_pdu.h
INCS += evcoap_srv.h

INCS += evcoap_filesys.h

include incs.mk
