# Included by proxy/ server/ and client/

CFLAGS += $(LIBU_CFLAGS)
CFLAGS += $(LIBEVENT_CFLAGS)

ifdef SHLIB
  LDFLAGS += -L../../src -levcoap
  LDFLAGS += $(LIBU_LDFLAGS)
  LDFLAGS += $(LIBEVENT_LDFLAGS)
else
  LDADD += ../../src/libevcoap.a
  LDADD += $(LIBEVENT_LDADD)
  LDADD += $(LIBU_LDADD)
endif

DPADD += $(LDADD)
